# This script is for cleaning my data

In [1]:
# Load libraries
import pandas as pd
import numpy as np
import duckdb

In [2]:
# Read in data
crayfish = pd.read_csv("data/knb-lter-ntl.128.8/Biocom_pred_prey_crayfish.csv")
prey = pd.read_csv("data/knb-lter-ntl.128.8/Biocom_pred_prey_diet.csv")
fish = pd.read_csv("data/knb-lter-ntl.128.8/Biocom_pred_prey_fish.csv")
fishscales = pd.read_csv("data/knb-lter-ntl.128.8/Biocom_pred_prey_fishscales.csv")

In [ ]:
# Print crayfish dataframe
crayfish.head()

,year,sampledate,Species,GutLabel,Carap_Length,Chela_Length_R,Chela_Length_L,Sex,State,Count
0,2001,2001-05-29,RB,rb01,NaN,NaN,NaN,NaN,NaN,NaN
1,2001,2001-05-29,RB,rb09,NaN,8.5,8.2,NaN,NaN,NaN
2,2001,2001-05-29,SMB,smb02,NaN,8.7,NaN,NaN,NaN,NaN
3,2001,2001-05-29,SMB,smb03,NaN,NaN,NaN,NaN,NaN,NaN
4,2001,2001-05-29,SMB,smb04,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Print all prey columns
pd.set_option('display.max_columns', None)
prey.head()

,YEAR,SAMPLEDATE,SPECIES,GUTLABEL,SCALELABEL,LENGTH,WEIGHT,ODONATA,NET_WT_ODONATA,EPHEMEROPTERA,NET_WT_EPHEMEROPTERA,CRAYFISH,NET_WT_CRAYFISH,FISH,NET_WT_FISH,SMELT,NET_WT_SMELT,BLUNTNOSE,NET_WT_BLUNTNOSE,MIMICSHINER,NET_WT_MIMICSHINER,OTHER_FISH,NET_WT_OTHER_FISH,DIPTERA,NET_WT_DIPTERA,TRICHOPTERA,NET_WT_TRICHOPTERA,HEMIPTERA,NET_WT_HEMIPTERA,CLADOCERA,NET_WT_CLADOCERA,HYDROCARINA,NET_WT_HYDROCARINA,COLEOPTERANS,NET_WT_COLEOPTERANS,AMPHIPOD,NET_WT_AMPHIPOD,EMERGENT_AQUATICS,NET_WT_EMERGENT_AQUATICS,TERRESTRIAL_INVERTS,NET_WT_TERRESTRIAL_INVERTS,OTHER,NET_WT OTHER,NOTES
0,2000,2000-05-29,RB,rbx,rbx,NaN,NaN,bits,0.017,0,0,1,0.006,0,0,na,na,na,na,na,na,na,na,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0,1,0.006,0,0,NaN
1,2000,2000-05-29,RB,rb01,rb01,174,125,0,0,0,0,1,0.63,0,0,na,na,na,na,na,na,na,na,bits,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0,0,0,0,0,NaN
2,2000,2000-05-29,RB,rb02,rb02,226,300,leg,0,0,0,bits,0.003,0,0,na,na,na,na,na,na,na,na,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0,0,0,0,0,NaN
3,2000,2000-05-29,RB,rb03,rb03,179,125,0,0,0,0,0,0,0,0,na,na,na,na,na,na,na,na,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0,0,0,0,0,NaN
4,2000,2000-05-29,RB,rb04,rb04,208,200,0,0,0,0,0,0,0,0,na,na,na,na,na,na,na,na,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0,0,0,0,0,NaN

In [ ]:
# Print fish dataframe
fish.head()

   Year  SampleDate Species GutLabel        PreySpecies  PreyLength  Count
0  2001  2001-06-12     LMB    lmb01  unidentified fish         NaN    NaN
1  2001  2001-06-12     SMB    smb07  unidentified fish         NaN    NaN
2  2001  2001-06-12     SMB    smb08              smelt        58.7    NaN
3  2001  2001-06-12     SMB    smb08              smelt        47.8    NaN
4  2001  2001-06-12     SMB    smb09  unidentified fish         NaN    NaN

In [ ]:
# Print fishscales dataframe
fishscales.head()

   year  sampledate Species ScaleLabel  Length  Weight
0  2000  2000-05-29      RB       rb01     174   125.0
1  2000  2000-05-29      RB       rb02     226   300.0
2  2000  2000-05-29      RB       rb03     179   125.0
3  2000  2000-05-29      RB       rb04     208   200.0
4  2000  2000-05-29      RB       rb05     193   150.0

In [7]:
# Remove unececarry columns from prey data frame
# These are being removed becuase they are either too messy to work with or are not useful for answering my question
cols_to_drop = [
    "NOTES", "OTHER", "TERRESTRIAL_INVERTS", "EMERGENT_AQUATICS",
    "AMPHIPOD", "COLEOPTERANS", "HYDROCARINA", "CLADOCERA",
    "HEMIPTERA", "TRICHOPTERA", "DIPTERA", "NET_WT_OTHER_FISH",
    "OTHER_FISH", "MIMICSHINER", "BLUNTNOSE", "SMELT", "FISH",
    "CRAYFISH", "EPHEMEROPTERA", "ODONATA"
]

# Drop columns from prey
prey = prey.drop(columns=cols_to_drop)

# Fix the space in prey column name
prey = prey.rename(columns={'net_wt other': 'net_wt_other'})

In [8]:
# Standardize all column names to lowercase, to make it easier to work with them
prey = prey.rename(columns=str.lower)
fish = fish.rename(columns=str.lower)
crayfish = crayfish.rename(columns=str.lower)
fishscales = fishscales.rename(columns=str.lower)
fish

     year  sampledate species gutlabel        preyspecies  preylength  count
0    2001  2001-06-12     LMB    lmb01  unidentified fish         NaN    NaN
1    2001  2001-06-12     SMB    smb07  unidentified fish         NaN    NaN
2    2001  2001-06-12     SMB    smb08              smelt        58.7    NaN
3    2001  2001-06-12     SMB    smb08              smelt        47.8    NaN
4    2001  2001-06-12     SMB    smb09  unidentified fish         NaN    NaN
..    ...         ...     ...      ...                ...         ...    ...
628  2004  2004-09-16      WE     we06          smelt YOY        32.0    NaN
629  2004  2004-09-16      WE     we07          smelt YOY        46.4    5.0
630  2004  2004-09-16      WE     we07          smelt YOY        43.0    NaN
631  2004  2004-09-16      WE     we07          smelt YOY        33.2    NaN
632  2004  2004-09-16      WE     we07          smelt YOY        40.2    NaN

[633 rows x 7 columns]

In [ ]:
# Replace placeholder/missing value codes with NA
# This is very necessary for 'gutlabel' and 'scalelabel' because they are both primary keys
fish['gutlabel'] = fish['gutlabel'].replace('nolabel', pd.NA)
crayfish['gutlabel'] = crayfish['gutlabel'].replace('nolabel', pd.NA)
prey['scalelabel'] = prey['scalelabel'].replace({'nc': pd.NA, 'empty': pd.NA, 'na': pd.NA, 'rbx': pd.NA})
prey = prey.replace({'na': pd.NA, 'nc': pd.NA})

# Fix 'we007' typo in fish
# Database can't be created unless done
fish['gutlabel'] = fish['gutlabel'].replace('we007', 'we07')

In [10]:
# Drop NAs in predator_fish["scalelabel"] and prey["gutlabel"]
# These will both be PKs and there can't be NAs in PKs
fishscales = fishscales.dropna(subset=["scalelabel"])
prey = prey.dropna(subset=["gutlabel"])

# Drop duplicates in predator_fish["scalelabel"] and prey["gutlabel"]
# These will both be PKs and there can't be duplicates in PKs
fishscales = fishscales.drop_duplicates(subset="scalelabel")
prey = prey.drop_duplicates(subset="gutlabel")

In [11]:
# Export clean CSVs
prey.to_csv('data/clean_data/diet.csv', index=False)
fishscales.to_csv('data/clean_data/fishscales.csv', index=False)
fish.to_csv('data/clean_data/fish.csv', index=False)
crayfish.to_csv('data/clean_data/crayfish.csv', index=False)

In [2]:
# Create database file
con = duckdb.connect("database/biocomplexity.duckdb")

# Run entire schema file
con.execute(open("Biocomplexity_database.sql", "r").read())

In [3]:
# Close Database
con.close()